## Spring DataSource
spring.datasource.url=jdbc:postgresql://ep-wild-silence-a96cpr66-pooler.gwc.azure.neon.tech/bazyjava?user=bazyjava_owner&password=npg_5YzTPkaKCv2b&sslmode=require
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
## Spring JPA
## The SQL dialect makes Hibernate generate better SQL for the chosen database
## (Postgres 9.5 and later)
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
## Validation or export of schema DDL to the database (create, create-drop, validate, update, none)
#spring.jpa.hibernate.ddl-auto=update
## Logging JPA Queries
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
## Spring Security
## HTTP authentication credentials
#spring.security.user.name=admin
#spring.security.user.password=admin

# Odkomentuj te linie
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
server.port=8081
rest.base.url=http://localhost:8081
rest.user.name=admin1
rest.user.password=admin1

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html